version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-dichvucong
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DEBUG=False
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - LOG_LEVEL=INFO
      - ENABLE_CACHE=True
      - CACHE_MAX_SIZE=1000
    env_file:
      - .env
    volumes:
      - ./embeddings:/app/embeddings
      - ./data:/app/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
