version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-dichvucong
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - DEBUG=False
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=2
      - LOG_LEVEL=INFO
      - ENABLE_CACHE=True
      - CACHE_MAX_SIZE=500
      - CACHE_TTL=3600
      - SIMILARITY_THRESHOLD=1.2
      - TOP_K_DEFAULT=8
      - LLM_TIMEOUT=60
    env_file:
      - .env
    volumes:
      - ./embeddings:/app/embeddings
      - ./data:/app/data:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - chatbot-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1536M
        reservations:
          cpus: '0.5'
          memory: 768M

networks:
  chatbot-network:
    driver: bridge
